### ISSUE TITLE
repository does not exist intelanalytics/ipex-llm-inference-cpp-xpu

### ISSUE THREAD

**Issue by TacitTactics** [intel/ipex-llm#13056]
**Describe the bug**
The repo intelanalytics/ipex-llm-inference-cpp-xpu is no longer on dockerhub

**How to reproduce**
Steps to reproduce the error:
1. run docker pull intelanalytics/ipex-llm-inference-cpp-xpu:latest

**Screenshots**

![Image](https://github.com/user-attachments/assets/c71097d0-4197-47a1-9065-d9cce1373349)

![Image](https://github.com/user-attachments/assets/0db39309-b1c9-4ed0-bc42-5d15cb6ded2a)

**Comment by fallenleavesgocrunch** [comment]
Same here.

**Comment by bermudahonk** [comment]
Hello,
to anyone who has been using that image in their own compose-files, you can/have to substitute the original image with a build rule like this to make things work as "usual" again:
```
    # before (simply pull the image)
    image: docker.io/intelanalytics/ipex-llm-inference-cpp-xpu:latest
    container_name: intel-llm
    # other stuff ...
```
```
    # now (build the image)
    image: intelanalytics/ipex-llm-inference-cpp-xpu:latest
    build:
      # this is the folder you cloned the repository to
      # ... valid only relative to the path of your compose file!
      context: ./ipex-llm/docker/llm/inference-cpp/
      dockerfile: ./Dockerfile
    container_name: intel-llm
    # other stuff ...
```
Where you cloned the github repository with:
```
github clone https://github.com/intel/ipex-llm.git <dir-of-your-docker-compose-file>
```
