### ISSUE TITLE
4xARC 770 on w5-3423 slow performance (half of what is reported here)

### ISSUE THREAD

**Issue by flekol** [intel/ipex-llm#13214]
# Describe the bug
I observe quite bad performance with my 4xARC770 setup with xeon w5-3423, 128 GB DDR5 and Asus w790 ACE. 
Main Question: I suppose with this setup i'm quite close to what you got. So what am i missing. What should be enabled in bios. **Could you share a bit more on how did you configure your system etc...?** 

GPUS are connected to PCIe 5 (does not really matter, as they are PCIe4 anyway). In theory they get good speed (all of them 18 GBPS, so inference should not be a problem)

```
sudo xpu-smi diag -d 0 --singletest 5

+------------------+-------------------------------------------------------------------------------+
| Device ID        | 0                                                                             |
+------------------+-------------------------------------------------------------------------------+
| Integration PCIe | Result: Fail                                                                  |
|                  | Message: Fail to check PCIe bandwidth. Its bandwidth is 17.995 GBPS.          |
|                  |   Unconfigured or invalid threshold. Fail on copy engine group 1.             |
+------------------+-------------------------------------------------------------------------------+
```

I'm on **ubuntu 22.04** and i installed everything as in your tutorial. Out of tree, etc. Same kernel.... After quite some testing i even compiled out of tree driver myself from the backports repo.... Same results

I locked freqs:
```
 sudo xpu-smi config -d 0 -t 0 --frequencyrange 2400,2400
 sudo xpu-smi config -d 1 -t 0 --frequencyrange 2400,2400
 sudo xpu-smi config -d 2 -t 0 --frequencyrange 2400,2400
 sudo xpu-smi config -d 3 -t 0 --frequencyrange 2400,2400
```

```
sudo cpupower frequency-set -g performance
sudo cpupower frequency-set -d 4.0GHz
```

and still just a bit of improvement.

## Tests with model=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B on 4xARC sym-int4
I get roughly half of what you are getting whatever i do

```
============ Serving Benchmark Result ============
Successful requests:                     1
Benchmark duration (s):                  35.40
Total input tokens:                      1024
Total generated tokens:                  512
Request throughput (req/s):              0.03
Output token throughput (tok/s):         14.46
Total Token throughput (tok/s):          43.39
---------------Time to First Token----------------
Mean TTFT (ms):                          1332.15
Median TTFT (ms):                        1332.15
P99 TTFT (ms):                           1332.15
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          66.67
Median TPOT (ms):                        66.67
P99 TPOT (ms):                           66.67
---------------Inter-token Latency----------------
Mean ITL (ms):                           66.67
Median ITL (ms):                         66.36
P99 ITL (ms):                            74.45
==================================================


```

Also my GPUs don't go above 110W for a signle request (when i do 32 requrest then it goes up by a lot, but not for a single (the picture is from FP8 though))
![e0c1656bd3487b0f83c704fb1ddede22.png](:/5dcf454b670341f1b9f24c6188e30355)

My tests were performed with a custom docker based on **intelanalytics/ipex-llm-serving-xpu:latest** (build today). But i tried a lot other builds and the performance does not really differ

```
FROM intelanalytics/ipex-llm-serving-xpu:latest

WORKDIR /temp

SHELL ["/bin/bash", "-c"]

WORKDIR /llm
RUN . /opt/intel/1ccl-wks/setvars.sh

ENTRYPOINT numactl -C 0-11 python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server \
  --served-model-name ${served_model_name} \
  --quantization ${quantization} \
  --model $model \
  --port $port \
  --trust-remote-code \
  --block-size ${block_size} \
  --gpu-memory-utilization ${gpu_memory_utilization} \
  --device xpu \
  --dtype $dtype \
  --enforce-eager \
  --load-in-low-bit ${load_in_low_bit} \
  --max-model-len ${max_model_len} \
  --max-num-batched-tokens ${max_num_batched_tokens} \
  --max-num-seqs ${max_num_seqs} \
  --tensor-parallel-size ${tensor_parallel_size} \
  --pipeline-parallel-size ${pipeline_parallel_size} \
  --disable-async-output-proc \
  --distributed-executor-backend ray

```

```
services:
  vllm-ipex:
    image: intelanalytics/ipex-llm-serving-xpu-custom:latest
    container_name: vllm-ipex
    build:
      dockerfile: ./dockerfile/dockerfile
    volumes:
      - "/models/huggingface:/root/.cache/huggingface"
      - /cloud/custom/ipex-llm/:/ipex-llm
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    tty: true
    ports:
      - 8000:8000
    shm_size: "32g"
    environment:
      # Model selection
      - quantization=None
      - model=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
      - served_model_name=DeepSeek-R1-Distill-Qwen-32B

      # Timezone and device
      - TZ=Europe/Berlin
      - DEVICE=Arc

      # Intel/OneAPI/CCL/SYCL
      - SYCL_CACHE_PERSISTENT=1
      - CCL_WORKER_COUNT=1
      - FI_PROVIDER=shm
      - CCL_ATL_TRANSPORT=ofi
      - CCL_ZE_IPC_EXCHANGE=sockets
      - CCL_ATL_SHM=1
      - USE_XETLA=OFF
      - SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=2
      - TORCH_LLM_ALLREDUCE=0
      - VLLM_USE_V1=0
      - CCL_SAME_STREAM=1
      - CCL_BLOCKING_WAIT=0
      - IPEX_LLM_LOWBIT=fp8

      # vLLM/Serving
      - port=8000
      - gpu_memory_utilization=0.9
      - dtype=float16
      - block_size=8
      - load_in_low_bit=sym_int4
      - max_model_len=9000
      - max_num_batched_tokens=9000
      - max_num_seqs=32
      - tensor_parallel_size=4
      - pipeline_parallel_size=1
      - enforce_eager=true

    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

```

## ENV:
```
sudo ./env-check.sh
-----------------------------------------------------------------
PYTHON_VERSION=3.10.12
-----------------------------------------------------------------
Transformers is not installed.
-----------------------------------------------------------------
PyTorch is not installed.
-----------------------------------------------------------------
ipex-llm ./env-check.sh: line 58: pip: command not found
-----------------------------------------------------------------
IPEX is not installed.
-----------------------------------------------------------------
CPU Information:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             24
On-line CPU(s) list:                0-23
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) w5-3423
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 12
Socket(s):                          1
Stepping:                           8
CPU max MHz:                        4200.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4224.00
-----------------------------------------------------------------
Total CPU Memory: 125.294 GB
Memory Type: DDR5
-----------------------------------------------------------------
Operating System:
Ubuntu 22.04.5 LTS \n \l

-----------------------------------------------------------------
Linux aiflek 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
CLI:
    Version: 1.2.41.20250422
    Build ID: 00000000

Service:
    Version: 1.2.41.20250422
    Build ID: 00000000
    Level Zero Version: 1.21.1
-----------------------------------------------------------------
  Driver UUID                                     32352e31-332e-3333-3237-360000000000
  Driver Version                                  25.13.33276
  Driver UUID                                     32352e31-332e-3333-3237-360000000000
  Driver Version                                  25.13.33276
  Driver UUID                                     32352e31-332e-3333-3237-360000000000
  Driver Version                                  25.13.33276
  Driver UUID                                     32352e31-332e-3333-3237-360000000000
  Driver Version                                  25.13.33276
-----------------------------------------------------------------
Driver related package version:
ii  intel-fw-gpu                                   2025.13.2-398~22.04                     all          Firmware package for Intel integrated and discrete GPUs
ii  intel-i915-dkms                                1.25.1.17.250113.16+i1-1                all          Out of tree i915 driver.
-----------------------------------------------------------------
igpu not detected
-----------------------------------------------------------------
xpu-smi is properly installed.
-----------------------------------------------------------------
+-----------+--------------------------------------------------------------------------------------+
| Device ID | Device Information                                                                   |
+-----------+--------------------------------------------------------------------------------------+
| 0         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0018-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:18:00.0                                                        |
|           | DRM Device: /dev/dri/card0                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
| 1         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0036-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:36:00.0                                                        |
|           | DRM Device: /dev/dri/card1                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
| 2         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0054-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:54:00.0                                                        |
|           | DRM Device: /dev/dri/card2                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
| 3         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0072-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:72:00.0                                                        |
|           | DRM Device: /dev/dri/card3                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
GPU0 Memory size=16G
GPU1 Memory size=16G
GPU2 Memory size=16G
GPU3 Memory size=16G
-----------------------------------------------------------------
18:00.0 VGA compatible controller: Intel Corporation Device 56a0 (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Device 172f:3937
        Flags: bus master, fast devsel, latency 0, IRQ 91, NUMA node 0
        Memory at 9e000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 2f800000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at 9f000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
--
36:00.0 VGA compatible controller: Intel Corporation Device 56a0 (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Flags: bus master, fast devsel, latency 0, IRQ 94, NUMA node 0
        Memory at a8000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 3f800000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at a9000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
--
54:00.0 VGA compatible controller: Intel Corporation Device 56a0 (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Flags: bus master, fast devsel, latency 0, IRQ 97, NUMA node 0
        Memory at b3000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 4f800000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at b4000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
--
72:00.0 VGA compatible controller: Intel Corporation Device 56a0 (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Flags: bus master, fast devsel, latency 0, IRQ 100, NUMA node 0
        Memory at bd000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 5f800000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at be000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
-----------------------------------------------------------------

```

![Image](https://github.com/user-attachments/assets/eb132f5e-079f-493b-9885-ae97f1a14886)
